# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1028ca9d68711d77bb453ea8951143b68e102aede637f064fa1fe51b26a74501808a1c7bfc7e73c352bacc4d7ca2d33219c92aac6fb6861e25d4718b7b7d1c68

test:
  secret_key_base: e2e3f6ad0da6097d08ec287d7943daaa2260175ed2e04f15ee8780cceeffb219af54df2ddb8c8047c7e1e709f5c79bde4c010682280f39e61bc8429b8b2c82e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
